# Generated by scripts/generate_contract.py. Do not edit.
from __future__ import annotations

from typing import Annotated, Literal
from pydantic import BaseModel, Field

APP_VERSION = '1.3.0'
PROTOCOL_VERSION = 2
AUDIO_VERSION = 1
SAMPLE_RATE = 16000
FRAME_MS = 100
HEADER_SIZE = 16
MAGIC = 165
FLAG_LIVE = 1
FLAG_DISCONTINUITY = 2


TargetLanguage = Literal['es', 'en']


class SensePayload(BaseModel):
    pos: list[str] = Field(default_factory=list)
    glosses_es: list[str] = Field(default_factory=list)
    glosses_en: list[str] = Field(default_factory=list)


class DictPayload(BaseModel):
    id: int
    headword: str
    readings: list[str] = Field(default_factory=list)
    common: bool = False
    freq_rank: int | None = None
    senses: list[SensePayload] = Field(default_factory=list)


class Token(BaseModel):
    i: int
    span: tuple[int, int]
    surface: str
    lemma: str
    kana: str
    romaji: str
    pos: list[str] = Field(default_factory=list)
    pos_label: str = ''
    chain: list[str] = Field(default_factory=list)
    clickable: bool = False
    entry: DictPayload | None = None


class SessionStart(BaseModel):
    type: Literal['session.start'] = 'session.start'
    protocol_version: int
    app_version: str = ''
    video_id: str = ''
    url: str = ''
    is_live: bool = False
    media_time_ms: int = 0
    source: Literal['ja'] = 'ja'
    target: TargetLanguage = 'es'
    profile: str = 'n4'


class SessionStop(BaseModel):
    type: Literal['session.stop'] = 'session.stop'


class SessionConfigure(BaseModel):
    type: Literal['session.configure'] = 'session.configure'
    target: TargetLanguage


class ControlFlush(BaseModel):
    type: Literal['control.flush'] = 'control.flush'
    reason: Literal['seek', 'pause', 'rate', 'manual'] = 'manual'
    media_time_ms: int = 0


class Ping(BaseModel):
    type: Literal['ping'] = 'ping'
    t: int = 0


class SessionReady(BaseModel):
    type: Literal['session.ready'] = 'session.ready'
    session_id: str
    asr_model: str
    device: str
    compute_type: str
    sample_rate: int
    frame_ms: int
    protocol_version: int
    app_version: str
    target: TargetLanguage = 'es'


class AsrPartial(BaseModel):
    type: Literal['asr.partial'] = 'asr.partial'
    committed: str
    tentative: str
    media_start_ms: int


class AsrFinal(BaseModel):
    type: Literal['asr.final'] = 'asr.final'
    segment_id: int
    text: str
    media_start_ms: int
    media_end_ms: int
    reason: str
    latency_ms: float


class MtFinal(BaseModel):
    type: Literal['mt.final'] = 'mt.final'
    segment_id: int
    text: str
    target: TargetLanguage = 'es'
    text_es: str = ''
    provider: str
    media_start_ms: int
    media_end_ms: int
    latency_ms: float


class NlpTokens(BaseModel):
    type: Literal['nlp.tokens'] = 'nlp.tokens'
    segment_id: int
    tokens: list[Token] = Field(default_factory=list)
    analysis_ms: float = 0.0


class MetricsTick(BaseModel):
    type: Literal['metrics.tick'] = 'metrics.tick'
    end_to_end_ms_p50: float = 0.0
    end_to_end_ms_p95: float = 0.0
    whisper_processing_ms_p50: float = 0.0
    audio_buffer_ms: float = 0.0
    dropped_audio_chunks: int = 0
    partial_transcripts: int = 0
    final_transcripts: int = 0
    passes: int = 0
    skipped_silent: int = 0
    rejected: dict[str, int] = Field(default_factory=dict)
    nlp_ms_p50: float = 0.0
    translation_latency_ms_p50: float = 0.0
    translations: int = 0
    dropped_translations: int = 0
    mt_provider: str = 'none'
    gpu_used_mb: float = 0.0
    gpu_total_mb: float = 0.0
    cpu_pct: float = 0.0
    ram_mb: float = 0.0


class ErrorMessage(BaseModel):
    type: Literal['error'] = 'error'
    code: str
    message: str
    fatal: bool = False


class Pong(BaseModel):
    type: Literal['pong'] = 'pong'
    t: int = 0


ClientMessage = Annotated[SessionStart | SessionStop | SessionConfigure | ControlFlush | Ping, Field(discriminator="type")]


ServerMessage = Annotated[SessionReady | AsrPartial | AsrFinal | MtFinal | NlpTokens | MetricsTick | ErrorMessage | Pong, Field(discriminator="type")]
