"""Generate Python/TypeScript from protocol/schema.json and versions from VERSION.

Only the JSON Schema subset used by this contract is supported; unknown shapes
fail loudly. No network, third-party generator or model downloads are needed.
Run with --check in tests/CI to detect edits to generated files or stale versions.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def type_name(node: dict, *, ts: bool) -> str:
    if "$ref" in node:
        return node["$ref"].rsplit("/", 1)[1]
    values = node.get("enum", [node["const"]] if "const" in node else None)
    if values is not None:
        return " | ".join(json.dumps(v) for v in values) if ts else f"Literal[{', '.join(repr(v) for v in values)}]"
    union = node.get("anyOf", node.get("oneOf"))
    if union:
        return " | ".join(type_name(part, ts=ts) for part in union)
    kind = node.get("type")
    if kind == "array":
        if "prefixItems" in node:
            parts = ", ".join(type_name(part, ts=ts) for part in node["prefixItems"])
            return f"[{parts}]" if ts else f"tuple[{parts}]"
        inner = type_name(node["items"], ts=ts)
        return f"Array<{inner}>" if ts else f"list[{inner}]"
    if kind == "object" and isinstance(node.get("additionalProperties"), dict):
        inner = type_name(node["additionalProperties"], ts=ts)
        return f"Record<string, {inner}>" if ts else f"dict[str, {inner}]"
    primitives = {"string": ("str", "string"), "integer": ("int", "number"),
                  "number": ("float", "number"), "boolean": ("bool", "boolean"), "null": ("None", "null")}
    if kind not in primitives:
        raise ValueError(f"Unsupported schema shape: {node}")
    return primitives[kind][ts]


def render(schema: dict, version: str) -> tuple[str, str]:
    py = ['# Generated by scripts/generate_contract.py. Do not edit.',
          'from __future__ import annotations', '',
          'from typing import Annotated, Literal', 'from pydantic import BaseModel, Field', '']
    ts = ['// Generated by scripts/generate_contract.py. Do not edit.', '']
    for name, value in {"app_version": version, **schema["x-youjp"]}.items():
        py.append(f"{name.upper()} = {value!r}")
        ts.append(f"export const {name.upper()} = {json.dumps(value)};")
    for name, definition in schema["$defs"].items():
        py.extend(['', ''])
        ts.append('')
        if "properties" not in definition:
            kind = type_name(definition, ts=False)
            if "oneOf" in definition:
                kind = f'Annotated[{kind}, Field(discriminator="type")]'
            py.append(f"{name} = {kind}")
            ts.append(f"export type {name} = {type_name(definition, ts=True)};")
            continue
        py.append(f"class {name}(BaseModel):")
        ts.append(f"export interface {name} {{")
        for field, node in definition["properties"].items():
            default = ''
            if "default" in node:
                val = node["default"]
                default = ' = Field(default_factory=list)' if val == [] else ' = Field(default_factory=dict)' if val == {} else f' = {val!r}'
            elif field not in definition.get("required", []):
                raise ValueError(f"{name}.{field}: optional fields need an explicit default")
            py.append(f"    {field}: {type_name(node, ts=False)}{default}")
            # All server fields are serialized after defaults are applied.
            ts.append(f"  {field}: {type_name(node, ts=True)};")
        ts.append('}')
    return '\n'.join(py) + '\n', '\n'.join(ts) + '\n'


def outputs(root: Path = ROOT) -> dict[Path, str]:
    version = (root / "VERSION").read_text(encoding="utf-8").strip()
    if not re.fullmatch(r"\d+\.\d+\.\d+", version):
        raise ValueError("VERSION must be major.minor.patch (Chrome manifest compatible)")
    schema = json.loads((root / "protocol/schema.json").read_text(encoding="utf-8"))
    py, ts = render(schema, version)
    result = {
        # Keep the contract at package root. Importing a module below
        # ``youjp.ws`` executes ws/__init__.py first, which imports the ASR
        # worker and therefore config.py, creating a config -> ws -> ASR ->
        # config cycle during a clean installer run.
        root / "backend/youjp/contract.py": py,
        root / "extension/src/generated/protocol.ts": ts,
        root / "backend/youjp/_version.py": f'# Generated from VERSION. Do not edit.\n__version__ = "{version}"\n',
    }
    for relative in ("extension/package.json", "extension/package-lock.json"):
        path = root / relative
        data = json.loads(path.read_text(encoding="utf-8"))
        data["version"] = version
        if "packages" in data:
            data["packages"][""]["version"] = version
        result[path] = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, content in outputs().items():
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        stale.append(str(path.relative_to(ROOT)))
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        print(("Stale generated files: " if args.check else "Generated: ") + ", ".join(stale))
    else:
        print("Protocol and versions are synchronized.")
    return int(args.check and bool(stale))


if __name__ == "__main__":
    raise SystemExit(main())
